### ISSUE TITLE
Fly fishing rick

### ISSUE THREAD

**Issue by DeFlanko** [Shmakov/Rick-and-Morty-Characters#1]
Last episode of season three - Fly-fishing Rick.

**Comment by Jasparigus** [comment]
That was actually just normal Rick pretending to be Fly-Fishing Rick to clear his name

**Comment by Shmakov** [comment]
I agree with @Jasparigus here. That was Rick camouflaged as another dimension version of himself.

**Comment by DeFlanko** [comment]
Still, we learned of a fly fishing rick.
