### ISSUE TITLE
I think you missed a couple things...

### ISSUE THREAD

**Issue by jadshep** [Shmakov/Rick-and-Morty-Characters#2]
It was all but confirmed that the Rick and Morty we followed though most of Mortynight Run were from a different dimension. This dimension is the same that the entirety of Total Rickall took place in. This means that the Rick, Morty, Beth, Summer, and Jerry in this whole episode are completely new, and probably never seen again. These Rick and Mortys would have also appeared in Mortynight Run.

Also, in Morty's Mind Blowers, didn't they move to a new dimension after Morty messed with squirrels? It's not clear when, but at some point all non Rick and Morty characters in that dimension should stop and should have a new version.

**Comment by Shmakov** [comment]
> Mortynight Run, It was all but confirmed..

Could you please provide any sources for that?

> Also, in Morty's Mind Blowers..

While you might be right, it is all not really clear. http://rickandmorty.wikia.com/wiki/Morty%27s_Mind_Blowers#Series_continuity

**Comment by jadshep** [comment]
Here is the video outlining what may have happened: https://youtu.be/W1Kgl9aqOnI

Here is the same guy talking about how the writers actually addressed his video: https://youtu.be/g6ZCfF49B8g

They are all joking around, and they don't really confirm it, but I think it's enough to consider it canon until other information comes out disproving it.

BTW, it's super cool you took the time to put this together! It must have taken an obscene amount of time.
