### ISSUE TITLE
Ethan

### ISSUE THREAD

**Issue by Sammo21** [Shmakov/Rick-and-Morty-Characters#4]
There are actually two different versions of Ethan that we see. He shows up in Anatomy Park  in Season 1(C-137) but theoretically that Ethan is either dead or a Cronenberg. The Ethan we see show up in Season 3 is from a different dimension...shouldn't that be a different listing?

**Comment by Shmakov** [comment]
You are probably right :) Please see Issue #3 for my explanation.
